/*
   This file has been generated by IDA.
   It contains local type definitions from
     /home/juergen/workspace/SELZ80Trainer/SELRom.idb
*/

/*    1 */
enum IC8279
{
  IC8279_Data = 0x0,
  IC8279_Ctrl = 0x1,
  IC8279_Data_mirrow = 0x2,
  IC8279_Ctrl_mirrow = 0x3,
};

/*    2 */
enum PIO_8255
{
  PIO_8255_PortA = 0x4,
  PIO_8255_PortB = 0x5,
  PIO_8255_PortC = 0x6,
  PIO_8255_CntrlStatus = 0x7,
};

/*    3 */
enum LS73_90_SigleStepCntr
{
  LS73_90_P8 = 0x8,
  LS73_90_P9 = 0x9,
  LS73_90_PA = 0xA,
  LS73_90_PB = 0xB,
};

/*    4 */
enum LS244_377BinIO
{
  BinIO_PC = 0xC,
  BinIO_PD = 0xD,
  BinIO_PE = 0xE,
  BinIO_PF = 0xF,
};

/*    5 */
enum Display74C97
{
  UserDisplay_1 = 0x10,
  UserDisplay_2 = 0x11,
  UserDisplay_3 = 0x12,
  UserDisplay_4 = 0x13,
  UserDisplay_5 = 0x14,
  UserDisplay_6 = 0x15,
};

/*    6 */
enum BlankPort
{
  BlankPort_16 = 0x16,
  BlankPort_16mirrow = 0x17,
};

/*    7 */
enum BUSDecoder
{
  BUSDecoder_1c = 0x1C,
  BUSDecoder_1D = 0x1D,
  BUSDecoder_1E = 0x1E,
  BUSDecoder_1F = 0x1F,
};

/*    8 */
enum Seg7
{
  seg7E = 0x1,
  seg7F = 0x2,
  seg7G = 0x4,
  seg7P = 0x8,
  seg7A = 0x10,
  seg7B = 0x20,
  seg7C = 0x40,
  seg7D = 0x80,
};

/*    9 */
enum SIO
{
  SIO8251_Dataport = 0x18,
  SIO8251_CntrPort = 0x19,
};

/*   10 */
enum KeyCode
{
  KeyCode_F = 0x0,
  KeyCode_E = 0x1,
  KeyCode_D = 0x2,
  KeyCode_C = 0x3,
  KeyCode_MM = 0x4,
  KeyCode_RN = 0x5,
  KeyCode_SS = 0x6,
  KeyCode_?? = 0x7,
  KeyCode_B = 0x8,
  KeyCode_A = 0x9,
  KeyCode_9 = 0xA,
  KeyCode_8 = 0xB,
  KeyCode_TR = 0xC,
  KeyCode_TW = 0xD,
  KeyCode_BP = 0xE,
  KeyCode_EX = 0xF,
  KeyCode_7 = 0x10,
  KeyCode_6 = 0x11,
  KeyCode_5 = 0x12,
  KeyCode_4 = 0x13,
  KeyCode_PLUS = 0x14,
  KeyCode_MINUS = 0x15,
  KeyCode_IN = 0x16,
  KeyCode_RL = 0x17,
  KeyCode_3 = 0x18,
  KeyCode_2 = 0x19,
  KeyCode_1 = 0x1A,
  KeyCode_0 = 0x1B,
  KeyCode_SD = 0x1C,
  KeyCode_SA = 0x1D,
  KeyCode_EN = 0x1E,
  KeyCode_RG = 0x1F,
};

/*   12 */
enum SIO8251Status
{
  TxRDY = 0,
  RxRDY = 1,
  TxEMPTY = 2,
  PE = 3,
  OE = 4,
  FE = 5,
  BRK = 6,
  DSRD = 7,
};

/*   14 */
enum SIO8251Contr
{
  TxEN = 0,
  DTR = 1,
  RxEN = 2,
  SBRK = 3,
  ER = 4,
  RTS = 5,
  IR = 6,
  EH = 7,
};

/*   15 */
enum Status_8297
{
  FIFOMSK = 0x7,
  LSD = 0xF,
  KBMASK = 0x1F,
  WRDIS = 0x80,
  CLFIFO = 0xC2,
};


/* End of file */
