/*
   This file has been generated by IDA.
   It contains local type definitions from
	 /svr/Downloads/Zilog/SEL80/SELRom.idb
*/

/*    1 */
enum KBC_8279 // uint8_t
{
  IC8279_Data = 0x0,
  IC8279_Ctrl = 0x1,
  IC8279_Data_mirrow = 0x2,
  IC8279_Ctrl_mirrow = 0x3,
};

/*    2 */
enum PIO_8255 // uint8_t
{
  PIO_8255_PortA = 0x4,
  PIO_8255_PortB = 0x5,
  PIO_8255_PortC = 0x6,
  PIO_8255_CntrlStatus = 0x7,
};

/*    3 */
enum IC74LS90Counter // uint8_t
{
  LS73_90_P8 = 0x8,
  LS73_90_P9 = 0x9,
  LS73_90_PA = 0xA,
  LS73_90_PB = 0xB,
};

/*    4 */
enum BinIO // uint8_t
{
  BinIO_PC = 0xC,
  BinIO_PD = 0xD,
  BinIO_PE = 0xE,
  BinIO_PF = 0xF,
};

/*    5 */
enum IC74C97Displ // uint8_t
{
  UserDisplay_1 = 0x10,
  UserDisplay_2 = 0x11,
  UserDisplay_3 = 0x12,
  UserDisplay_4 = 0x13,
  UserDisplay_5 = 0x14,
  UserDisplay_6 = 0x15,
  UserDisplay_Blank = 0x16,
  UserDisplay_Blank1 = 0x17,
};

/*    7 */
enum BUSDecoder // uint8_t
{
  BUSDecoder_1c = 0x1C,
  BUSDecoder_1D = 0x1D,
  BUSDecoder_1E = 0x1E,
  BUSDecoder_1F = 0x1F,
};

/*    8 */
enum Seg7 // uint8_t
{
  _E = 0x1,
  _F = 0x2,
  _G = 0x4,
  _P = 0x8,
  _A = 0x10,
  _B = 0x20,
  _C = 0x40,
  _D = 0x80,
};

/*    9 */
enum SIO_8251 // uint8_t
{
  SIO8251_Dataport = 0x18,
  SIO8251_CntrPort = 0x19,
};

/*   10 */
enum KeyCode // uint8_t
{
  KeyCode_F = 0x0,
  KeyCode_E = 0x1,
  KeyCode_D = 0x2,
  KeyCode_C = 0x3,
  KeyCode_MM = 0x4,
  KeyCode_RN = 0x5,
  KeyCode_SS = 0x6,
  KeyCode_RS = 0x7,
  KeyCode_B = 0x8,
  KeyCode_A = 0x9,
  KeyCode_9 = 0xA,
  KeyCode_8 = 0xB,
  KeyCode_TR = 0xC,
  KeyCode_TW = 0xD,
  KeyCode_BP = 0xE,
  KeyCode_EX = 0xF,
  KeyCode_7 = 0x10,
  KeyCode_6 = 0x11,
  KeyCode_5 = 0x12,
  KeyCode_4 = 0x13,
  KeyCode_PLUS = 0x14,
  KeyCode_MINUS = 0x15,
  KeyCode_IN = 0x16,
  KeyCode_RL = 0x17,
  KeyCode_3 = 0x18,
  KeyCode_2 = 0x19,
  KeyCode_1 = 0x1A,
  KeyCode_0 = 0x1B,
  KeyCode_SD = 0x1C,
  KeyCode_SA = 0x1D,
  KeyCode_EN = 0x1E,
  KeyCode_RG = 0x1F,
};

/*   12 */
enum SIO8251Status // uint8_t
{
  TxRDY,
  RxRDY,
  TxEMPTY,
  PE,
  OE,
  FE,
  BRK = 0x6,
  DSRD = 0x7,
};

/*   14 */
enum SIO8251Contr // uint8_t
{

	TxEN,	 // Transmitter enabled
	DTR,	 // Data Terminal Ready
	RxEN,	 // Receiver enabled
	SBRK,	 // Send BREAK
	ER,		 // Error reset
	RTS,	 // Request to Send
	IR,		 // Internal reset
	EH		 // Enter HUNT Mode
};


#define SELROM0START	0		// 0000.....0FFF 1 4 kb Eprom mit Betriebsprogramm (Typ 2732)
#define SELRAMSTART		0x1000  // 1000.....17FF 2 2 kb Ram (Typ 2106) Speicher
#define SELR1M0START	0x1800  // 1800.....1FFF 3 2 kb Ram/Eprom (2106/2716) - freie Fassung
#define SELR2M0START	0x2000  // 2000.....27FF 5 2 kb Ram/Eprom (2106/2716) - freie Fassung
#define SELBUSMAP		0x2800  // 2800.....2FFF dekodiert auf BUS
#define SELROM3START	0x3000  // 3000.....3FFF 4 4 kb Eprom (Typ 2732) - freie Fassung
#define SELNOTUSED		0x4000  // 4000.....FFFF nicht verwendet
#define SELRAMEND		0x0FFFF // End of memory.

#define SELExtend9		0x2808  // JP 2808h if 0xC3 code exist
#define SELExtendA		0x0E000 // JP e000h if 0xC3 code exist
#define SELExtendB		0x0E003 // JP e003h if 0xC3 code exist

/* End of file */
